version: "3.3"
services:
  thtgbot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - redis-net
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis_data:/data
    networks:
      - redis-net
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    expose:
      - "${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}

networks:
  redis-net:

volumes:
  redis_data: