# THORChain monitoring bot configuration file
# Rename it to "config.yaml"

log_level: INFO
sleep_before_start: 3


thor:
  network_id: "mainnet"

  node:
    node_url: "https://thornode.ninerealms.com/"
    rpc_node_url: "https://rpc.ninerealms.com/"

  midgard:
    tries: 3
    use_nodes: false
    public_url: "https://midgard.ninerealms.com/"
  #    public_url: "https://midgard.thorchain.info/"

  timeout: 2.0

  stable_coins:
    - ETH.USDC-0XA0B86991C6218B36C1D19D4A2E9EB0CE3606EB48
    - ETH.USDT-0XDAC17F958D2EE523A2206206994597C13D831EC7
    - ETH.USDT-0XA3910454BF2CB59B8B3A401589A3BACC5CA42306  # test
    - BNB.USDT-6D8
    - BNB.USDT-DC8  # test
    - BNB.BUSD-BD1
    - BNB.BUSD-BAF  # test
    - BNB.BUSD-74E  # test
    - TERRA.USD

  circulating_supply:
    # https://docs.etherscan.io/getting-started/creating-an-account
    ether_scan_key: PLEASEPUTANETHERSCANKEYHERE
    cache_time: 10m


telegram:
  bot:
    token: "insert the bot token from @BotFather here"
    username: "thor_infobot"
  common:
    loading_sticker: CAACAgIAAxkBAAIRx1--Tia-m6DNRIApk3yqmNWvap_sAALcAAP3AsgPUNi8Bnu98HweBA

  admins:
    - 12345  # List of TG admins

  buffer_chat: -12334  # a chat for uploading temporary photos (like photo-hosting), add this bot to it

  menu:
    node_op_tools:
      enabled: true

  inline_bot:
    enabled: true
    cache_time: 5m


discord:
  enabled: true
  bot:
    token: "token.for.discord.bot"


slack:
  enabled: true
  bot:
    app_token: xapp-1234134567
    client_id: "123.345"
    client_secret: 1234567890abcdef
    singing_secret: 1234567890abcdef


twitter: # (!) new
  enabled: true
  is_mock: false
  bot:
    consumer_key: "111"
    consumer_secret: "222"
    access_token: "333"
    access_token_secret: "444"


web:
  debug: false
  port: 8077
  host: 0.0.0.0
  public_url: https://settings.thornode.org
  #  public_url: https://test-settings.thornode.org
  serve_front_end: false  # false on production, this is work for nginx


# for message broadcasting
channels:
  - type: telegram
    name: "@thorchain_alert"  # live channel
    lang: eng
  - type: discord
    name: 322323232323  # channel ID
    lang: rus
  - type: twitter
    lang: eng-tw


node_op_tools:
  enabled: true

  watchdog:
    enabled: true
    disconnected_cable_timeout: 20m
  types:
    chain_height:
      # 'most_common' or 'max' or  'max_committee' (default)
      top_height_estimation_method: 'max_committee'
      min_committee_members: 3
    online_service:
      tcp_timeout: 1  # sec
      group_size: 60



native_scanner: # (!) new
  enabled: true

  prohibited_addresses:
    - "thor1dheycdevq39qlkxs2a6wuuzyn4aqxhve4qxtxt"
    - "thor17gw75axcnr8747pkanye45pnrwk7p9c3cqncsv"
    - "thor1g98cy3n9mmjrpn0sxmn63lztelera37n8n67c0"


names: # (!) new
  use_thor_name: false
  preconfig:
    "thor1dheycdevq39qlkxs2a6wuuzyn4aqxhve4qxtxt": "Reserve"
    "thor17gw75axcnr8747pkanye45pnrwk7p9c3cqncsv": "Bond Module"
    "thor1lj62pg6ryxv2htekqx04nv7wd3g98qf9gfvamy": "Standby Reserve"
    "thor1t60f02r8jvzjrhtnjgfj4ne6rs5wjnejwmj7fh": "Binance Cold"
    "thor1g98cy3n9mmjrpn0sxmn63lztelera37n8n67c0": "Pool Module"
    "thor1lrnrawjlfp6jyrzf39r740ymnuk9qgdgp29rqv": "Vested Wallet1"
    "thor16qnm285eez48r4u9whedq4qunydu2ucmzchz7p": "Vested Wallet2"
    "thor1505gp5h48zd24uexrfgka70fg8ccedafsnj0e3": "Treasury1"
    "thor14n2q7tpemxcha8zc26j0g5pksx4x3a9xw9ryq9": "Treasury2"
    "thor1y5lk3rzatghv9y4s4j90qt9ayq83e2dpf2hvzc": "Vesting 9R"
    "thor1ty6h2ll07fqfzumphp6kq3hm4ps28xlm2l6kd6": "crypto.com"
    "thor1egxvam70a86jafa8gcg3kqfmfax3s0m2g3m754": "TreasuryLP"


tx:
  enabled: true
  max_age: 1d
  fetch_period: 70
  tx_per_batch: 50
  max_page_deep: 5
  max_tx_per_single_message: 6

  exclamation:
    fee_usd_limit: 3000
    ilp_usd_limit: 5000
    slip_usd_limit: 5000

  liquidity:
    enabled: true
    min_usd_total: 50000
    usd_requirements_curve:
      - depth: 10000
        percent: 20
      - depth: 100000
        percent: 12
      - depth: 500000
        percent: 8
      - depth: 1000000
        percent: 5
      - depth: 10000000
        percent: 1.5

  swap:
    enabled: true
    min_usd_total: 5000
    usd_requirements_curve:
      - depth: 10000
        percent: 20
      - depth: 100000
        percent: 10
      - depth: 500000
        percent: 7
      - depth: 1000000
        percent: 4
      - depth: 10000000
        percent: 1.5

  donate:
    enabled: true
    min_usd_total: 1000
    usd_requirements_curve:
      - depth: 10000
        percent: 10
      - depth: 100000
        percent: 5
      - depth: 500000
        percent: 2.5
      - depth: 1000000
        percent: 1
      - depth: 10000000
        percent: 0.5

  refund:
    enabled: true
    min_usd_total: 50000
    usd_requirements_curve:
      - depth: 20000
        percent: 15  # if depth < 10_000 then
      - depth: 100000
        percent: 10  # if 10_000 <= depth < 100_000 then
      - depth: 500000
        percent: 8  # and so on...
      - depth: 1000000
        percent: 5
      - depth: 10000000
        percent: 1.5

  switch:
    enabled: true
    min_usd_total: 150000


price:
  enabled: true
  fetch_period: 60
  global_cd: 12h
  change_cd: 1h
  percent_change_threshold: 5
  price_graph:
    default_period: 7d

  bep2_reference: # (!) new
    cex: hitbtc
    pair: USDT

  ath:
    cooldown: 2m
    stickers:
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvF-zvjn4-XPhcr-M06zZUUvwF700AAIpAAM7cR8iDQ6e_eGNDLUeBA
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPol-zvRRRPSdC-Sr4lqhKsfNWWh3qAAJPAQACIjeOBHyVl0hMcbwXHgQ
      - CAACAgIAAxkBAAIPsF-zvVaSci3nhGf2-6l2YUEKcMKnAAICAAMUkqgdqsiIC2ZyV0oeBA
      - CAACAgIAAxkBAAIPsl-zvWI-Ihnnh0BSm6BM6DpYjYuJAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPwl-zyp2DJdPINcX6h0ZGesaakaMnAAJ9AwACbbBCA70TLvm2TbpTHgQ
      - CAACAgIAAxkBAAIPyV-zzEtVsFiaAWTVrJ8ROptFYUqjAAJFAAP3F4ErgJFXK7AarK4eBA
      - CAACAgIAAxkBAAJQsV_4emucc8THq6MbytL5PcclEG4NAAKMCwACLw_wBoRsyFANo_xWHgQ
      - CAACAgIAAxkBAAJQs1_4epK5KoxnhAJ3R5akKXpIfN1nAAKfAQACFkJrCmWMf9oXSSAlHgQ
      - CAACAgUAAxkBAAJQtV_4eqqciwvp9NCRdslyOoCKsOSaAAIdAAPRi-Yk3GCYqQrnOzceBA
      - CAACAgIAAxkBAAJQt1_4esnnDoR3NjLpgKHilirOZWybAAJsAAMUkqgduXN64vXUPDceBA
      - CAACAgUAAxkBAAJQuV_4eupYryWgJXeuLUu8xQsrfiBEAAIMAAPRi-Ykfll73qqZa3keBA
      - CAACAgUAAxkBAAJQu1_4eu8AAVG_deJgnwdKZcU9bsMYdgACGQAD0YvmJI2929l8C8ycHgQ
      - CAACAgUAAxkBAAJQvV_4ev8v5xXq_gABGb1O3g7UzdcZeAACHAAD0YvmJMnrKQclfN7VHgQ
      - CAACAgUAAxkBAAJQv1_4ewpDR4CoS3lWCVv2P0jEgZjfAAIUAAPRi-YkVzAp86uZwLMeBA
      - CAACAgUAAxkBAAJQw1_4ex7Ly2p8QAuLQvkeASXbgk9mAAIfAAPRi-YkQByn2GfGsIAeBA
      - CAACAgIAAxkBAAJQxV_4ezGuN6vz35bTfmLe4GPoT6GFAAKlAQACFkJrCqSMglNGCdzWHgQ
      - CAACAgUAAxkBAAJQtV_4eqqciwvp9NCRdslyOoCKsOSaAAIdAAPRi-Yk3GCYqQrnOzceBA
      - CAACAgIAAxkBAAJQt1_4esnnDoR3NjLpgKHilirOZWybAAJsAAMUkqgduXN64vXUPDceBA
      - CAACAgUAAxkBAAJQuV_4eupYryWgJXeuLUu8xQsrfiBEAAIMAAPRi-Ykfll73qqZa3keBA
      - CAACAgUAAxkBAAJQu1_4eu8AAVG_deJgnwdKZcU9bsMYdgACGQAD0YvmJI2929l8C8ycHgQ
      - CAACAgUAAxkBAAJQvV_4ev8v5xXq_gABGb1O3g7UzdcZeAACHAAD0YvmJMnrKQclfN7VHgQ
      - CAACAgIAAxkBAAKYGmAxSKM0wcVUir6olqJ8GUILs7PEAAI2AwACnNbnCqJFmbVS5co5HgQ
      - CAACAgIAAxkBAAKYGGAxSJmnC6uu7NyUkjwD2uQ2k8Z3AAITAwACnNbnCv7sKag-OU5jHgQ
      - CAACAgIAAxkBAAKYFmAxSI6jczWX5DMkK9N7D5U3arbZAAIDAQACVp29CgLl0XiH5fpPHgQ
      - CAACAgIAAxkBAAKYHGAxSOVmUIJnSALFOQmjvDUUhE8SAAIvAwACnNbnCp7xW8futGVHHgQ
      - CAACAgIAAxkBAAKYHmAxSPKMMhaVi529pPU-_ROhQlB_AAIUAAM7YCQUKWeBEgL3yOoeBA
      - CAACAgIAAxkBAAKYImAxSRLALhyBbigWlLSUzrLaf84mAAJVBgAC-gu2CMHtlUjSy95hHgQ
      - CAACAgIAAxkBAAKYJGAxSSC1U9D67zyg-7RJfjkork8EAAKMAAMWQmsKQo7-Yhc9TeIeBA
      - CAACAgIAAxkBAAKYJmAxST6CTOiOStfQ9CH7hqLiv0iWAAL8BgACRvusBG1XSZhZ24v-HgQ

  divergence:
    enabled: true
    cooldown: 12h

    public: # (!) new
      min_percent: 1.9
      max_percent: 5.5
    personal: # (!) new
      enabled: true
      cooldown: 30m


bep2:
  enabled: true
  fetch_period: 30
  min_usd: 300000
  flow_summary:
    enabled: true
    cooldown: 1d
  known_addresses:
    bnb1jzdy3vy3h0ux0j7qqcutfnsjm2xnsa5mru7gtj: "FTX"
    bnb142q467df6jun6rt5u2ar58sp47hm5f9wvz2cvg: "Binance 1"
    bnb1u2agwjat20494fmc6jnuau0ls937cfjn4pjwtn: "Binance 2"
    bnb1fnd0k5l4p3ck2j9x9dp36chk059w977pszdgdz: "Binance 3"
    bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23: "Binance Deposits"
    bnb1dtpty6hrxehwz9xew6ttj52l929cu8zehprzwj: "KuCoin Cold"
    bnb13q87ekxvvte78t2q7z05lzfethnlht5agfh4ur: "KuCoin Hot"
    bnb1apkwlqftwue7mcwvhe8zckxq030afecat9lkae: "Probit"
    bnb16e9kvc8846lht4y2yav777p6hweffcqvva757l: "HitBTC"
    bnb10af52w77pkehgxhnwgeca50q2t2354q4xamz5y: "MEXC"
    bnb165r4pxe862hetuz2l3wt4yx43uhh4ph9u0ptz6: "Unknown CEX"
    bnb1pv5vycd4xe3nu0msrewgf9tmfvam8yr3x6j97q: "Ascendex"
    bnb1axqc2gan462z6npw3c33srp4950mr5x28uc6wu: "THORChain Community"
    bnb13a7gyv5zl57c0rzeu0henx6d0tzspvrrakxxtv: "THORChain Operational"
    bnb1e4q8whcufp6d72w8nwmpuhxd96r4n0fstegyuy: "Burn address"
  cex_list:
    - bnb1jzdy3vy3h0ux0j7qqcutfnsjm2xnsa5mru7gtj
    - bnb142q467df6jun6rt5u2ar58sp47hm5f9wvz2cvg
    - bnb1u2agwjat20494fmc6jnuau0ls937cfjn4pjwtn
    - bnb1fnd0k5l4p3ck2j9x9dp36chk059w977pszdgdz
    - bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23
    - bnb1dtpty6hrxehwz9xew6ttj52l929cu8zehprzwj
    - bnb1apkwlqftwue7mcwvhe8zckxq030afecat9lkae
    - bnb16e9kvc8846lht4y2yav777p6hweffcqvva757l
    - bnb10af52w77pkehgxhnwgeca50q2t2354q4xamz5y
    - bnb165r4pxe862hetuz2l3wt4yx43uhh4ph9u0ptz6
    - bnb1pv5vycd4xe3nu0msrewgf9tmfvam8yr3x6j97q
    - bnb13q87ekxvvte78t2q7z05lzfethnlht5agfh4ur
  ignore_cex2cex: true


cap:
  enabled: true
  fetch_period: 120

  full:
    enabled: True
    full_limit_ratio: 0.995
    open_up_limit_ratio: 0.97

  raised:
    stickers:
      - CAACAgIAAxkBAAIKKmCLydn1J32d6Rawoy8AAZYxwCXnPQACLQADFJKoHX4nAr5MyGKYHwQ
      - CAACAgIAAxkBAAIKLGCLyeS4VTRUaSJDGhpCQ-51H8HHAAJGAAMUkqgdblkQIwX7yqsfBA
      - CAACAgIAAxkBAAIKMGCLyi1YmvVywp3aSZV7tuAzFUhLAAI9AAMUkqgdxLKS55dH2qkfBA
      - CAACAgIAAxkBAAIKRWCL-Q5NWNZJbYhHEA300U7qbZGWAAL4DgAC2GVZSLdSltiAcx7cHwQ


queue:
  enabled: true
  fetch_period: 60
  threshold:
    avg_period: 10m
    congested: 20
    free: 2
  cooldown: 3600
  watch_queues:
    - outbound
    - internal
    - swap


net_summary:
  enabled: true
  fetch_period: 120s
  notification:
    cooldown: 6h



pool_churn:
  enabled: true
  notification:
    cooldown: 1h
  fetch_period: 135s


node_info:
  enabled: true
  fetch_period: 5s  # for it must not be too slow for NodeOp tools accuracy
  geo_ip:
    expire: 48h

  churn:
    filter_nonsense: false

  version:
    enabled: true
    new_version_appears: # node joined/upgraded to unseen version
      enabled: true
      cooldown: 15m
    version_activates: # new active version (minimal active version)
      enabled: true
      cooldown: 15m
    upgrade_progress: # if not all act. nodes run same version, show upgrade progress every cooldown
      enabled: true
      cooldown: 2h


constants:
  mimir_change:
    enabled: true
  fetch_period: 130s

  voting:
    enabled: true
    notification:
      cooldown: 2h


chain_state:
  enabled: true
  fetch_period: 67s


last_block:
  enabled: true
  fetch_period: 30s
  chart:
    estimation_interval: 5m
  stuck_alert:
    time_limit: 120s
    repeat_cooldown: 24h
    chart_duration: 36h
  normal_block_time: 0.16666  # 1 block = 6 sec
  normal_block_speed_deviation_percent: 15
  low_block_speed_percent: -50
  high_block_speed_percent: 50


best_pools:
  enabled: true
  fetch_period: 30m
  num_of_top_pools: 5
  cooldown: 1d


blockchain:
  block_time: # block_time overriding... (optional)
    BTC: 10m
    ETH: 14s
