# rename it to "config.yaml"

log_level: INFO


thor:
  #  "testnet-multi" for MTCN
  #  "chaosnet-multi" for MCCN
  #  "chaosnet-bep2" for Bepswap Chaosnet
  network_id: "chaosnet-multi"


telegram:
  bot:
    token: "insert the bot token from @BotFather here"
    username: "thor_infobot"
  channels:
    - type: telegram
      name: "@thorchain_alert"  # live channel
      lang: eng
  common:
    loading_sticker: CAACAgIAAxkBAAIRx1--Tia-m6DNRIApk3yqmNWvap_sAALcAAP3AsgPUNi8Bnu98HweBA

  buffer_chat: -12334  # a chat for uploading temporary photos (like photo-hosting), add this bot to it

tx:
  enabled: true
  liquidity:
    max_age: 12h
    fetch_period: 70
    tx_per_batch: 50
    max_page_deep: 5
    min_usd_total: 50000
    usd_requirements_curve:
      - depth: 10000
        percent: 20  # if depth < 10_000 then 20% min
      - depth: 100000
        percent: 12  # if 10_000 <= depth < 100_000 then 20 % ... 12 %
      - depth: 500000
        percent: 8  # and so on...
      - depth: 1000000
        percent: 5
      - depth: 10000000
        percent: 1.5


price:
  enabled: true
  fetch_period: 60
  global_cd: 12h
  change_cd: 1h
  percent_change_threshold: 5
  price_graph:
    default_period: 7d
  ath:
    cooldown: 2m
    stickers:
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvF-zvjn4-XPhcr-M06zZUUvwF700AAIpAAM7cR8iDQ6e_eGNDLUeBA
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPol-zvRRRPSdC-Sr4lqhKsfNWWh3qAAJPAQACIjeOBHyVl0hMcbwXHgQ
      - CAACAgIAAxkBAAIPsF-zvVaSci3nhGf2-6l2YUEKcMKnAAICAAMUkqgdqsiIC2ZyV0oeBA
      - CAACAgIAAxkBAAIPsl-zvWI-Ihnnh0BSm6BM6DpYjYuJAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPul-zvjBr2Oc88YgFBNhMtktP4pCeAAJpAgACVp29Cta5X0h7RGRvHgQ
      - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
      - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
      - CAACAgIAAxkBAAIPwl-zyp2DJdPINcX6h0ZGesaakaMnAAJ9AwACbbBCA70TLvm2TbpTHgQ
      - CAACAgIAAxkBAAIPyV-zzEtVsFiaAWTVrJ8ROptFYUqjAAJFAAP3F4ErgJFXK7AarK4eBA
      - CAACAgIAAxkBAAJQsV_4emucc8THq6MbytL5PcclEG4NAAKMCwACLw_wBoRsyFANo_xWHgQ
      - CAACAgIAAxkBAAJQs1_4epK5KoxnhAJ3R5akKXpIfN1nAAKfAQACFkJrCmWMf9oXSSAlHgQ
      - CAACAgUAAxkBAAJQtV_4eqqciwvp9NCRdslyOoCKsOSaAAIdAAPRi-Yk3GCYqQrnOzceBA
      - CAACAgIAAxkBAAJQt1_4esnnDoR3NjLpgKHilirOZWybAAJsAAMUkqgduXN64vXUPDceBA
      - CAACAgUAAxkBAAJQuV_4eupYryWgJXeuLUu8xQsrfiBEAAIMAAPRi-Ykfll73qqZa3keBA
      - CAACAgUAAxkBAAJQu1_4eu8AAVG_deJgnwdKZcU9bsMYdgACGQAD0YvmJI2929l8C8ycHgQ
      - CAACAgUAAxkBAAJQvV_4ev8v5xXq_gABGb1O3g7UzdcZeAACHAAD0YvmJMnrKQclfN7VHgQ
      - CAACAgUAAxkBAAJQv1_4ewpDR4CoS3lWCVv2P0jEgZjfAAIUAAPRi-YkVzAp86uZwLMeBA
      - CAACAgUAAxkBAAJQw1_4ex7Ly2p8QAuLQvkeASXbgk9mAAIfAAPRi-YkQByn2GfGsIAeBA
      - CAACAgIAAxkBAAJQxV_4ezGuN6vz35bTfmLe4GPoT6GFAAKlAQACFkJrCqSMglNGCdzWHgQ
      - CAACAgUAAxkBAAJQtV_4eqqciwvp9NCRdslyOoCKsOSaAAIdAAPRi-Yk3GCYqQrnOzceBA
      - CAACAgIAAxkBAAJQt1_4esnnDoR3NjLpgKHilirOZWybAAJsAAMUkqgduXN64vXUPDceBA
      - CAACAgUAAxkBAAJQuV_4eupYryWgJXeuLUu8xQsrfiBEAAIMAAPRi-Ykfll73qqZa3keBA
      - CAACAgUAAxkBAAJQu1_4eu8AAVG_deJgnwdKZcU9bsMYdgACGQAD0YvmJI2929l8C8ycHgQ
      - CAACAgUAAxkBAAJQvV_4ev8v5xXq_gABGb1O3g7UzdcZeAACHAAD0YvmJMnrKQclfN7VHgQ
      - CAACAgIAAxkBAAKYGmAxSKM0wcVUir6olqJ8GUILs7PEAAI2AwACnNbnCqJFmbVS5co5HgQ
      - CAACAgIAAxkBAAKYGGAxSJmnC6uu7NyUkjwD2uQ2k8Z3AAITAwACnNbnCv7sKag-OU5jHgQ
      - CAACAgIAAxkBAAKYFmAxSI6jczWX5DMkK9N7D5U3arbZAAIDAQACVp29CgLl0XiH5fpPHgQ
      - CAACAgIAAxkBAAKYHGAxSOVmUIJnSALFOQmjvDUUhE8SAAIvAwACnNbnCp7xW8futGVHHgQ
      - CAACAgIAAxkBAAKYHmAxSPKMMhaVi529pPU-_ROhQlB_AAIUAAM7YCQUKWeBEgL3yOoeBA
      - CAACAgIAAxkBAAKYImAxSRLALhyBbigWlLSUzrLaf84mAAJVBgAC-gu2CMHtlUjSy95hHgQ
      - CAACAgIAAxkBAAKYJGAxSSC1U9D67zyg-7RJfjkork8EAAKMAAMWQmsKQo7-Yhc9TeIeBA
      - CAACAgIAAxkBAAKYJmAxST6CTOiOStfQ9CH7hqLiv0iWAAL8BgACRvusBG1XSZhZ24v-HgQ

cap:
  enabled: true
  fetch_period: 120

  full:
    enabled: True
    full_limit_ratio: 0.995

  raised:
    stickers:
      - CAACAgIAAxkBAAIKKmCLydn1J32d6Rawoy8AAZYxwCXnPQACLQADFJKoHX4nAr5MyGKYHwQ
      - CAACAgIAAxkBAAIKLGCLyeS4VTRUaSJDGhpCQ-51H8HHAAJGAAMUkqgdblkQIwX7yqsfBA
      - CAACAgIAAxkBAAIKMGCLyi1YmvVywp3aSZV7tuAzFUhLAAI9AAMUkqgdxLKS55dH2qkfBA
      - CAACAgIAAxkBAAIKRWCL-Q5NWNZJbYhHEA300U7qbZGWAAL4DgAC2GVZSLdSltiAcx7cHwQ


queue:
  enabled: true
  fetch_period: 60
  threshold:
    avg_period: 10m
    congested: 20
    free: 2
  cooldown: 3600


net_summary:
  enabled: true
  fetch_period: 120s
  notification:
    cooldown: 6h



pool_churn:
  enabled: true
  notification:
    cooldown: 1h
  fetch_period: 135s


node_info:
  enabled: true
  fetch_period: 140s
  geo_ip:
    expire: 48h

  version:
    enabled: true
    new_version_appears: # node joined/upgraded to unseen version
      enabled: true
      cooldown: 15m
    version_activates: # new active version (minimal active version)
      enabled: true
      cooldown: 15m
    upgrade_progress: # if not all act. nodes run same version, show upgrade progress every cooldown
      enabled: true
      cooldown: 2h


constants:
  mimir_change:
    enabled: true
  fetch_period: 130s


chain_state:
  enabled: true
  fetch_period: 67s
