# rename it to "config.yaml"

log_level: INFO

telegram:
  bot:
    token: "insert the bot token from @BotFather here"
  channels:
    - type: telegram
      name: "@thorchain_alert"  # live channel
      lang: eng


tx:
  stake_unstake:
    avg_n: 20
    threshold_mult: 5.0
    max_age_sec: 1200
    fetch_period: 70
    tx_per_batch: 50
    max_page_deep: 10
    min_usd_total: 10000

price:
  fetch_period: 60
  global_cd: 12h
  change_cd: 1h
  percent_change_threshold: 5

cap:
  fetch_period: 120


queue:
  fetch_period: 80
  steps:
    - 20
    - 50
    - 100
  cooldown: 3600
